<?php

namespace Kkxdev\AppleIap\Crypto;

/**
 * Embeds Apple Root CA G3 and Apple Root CA G2 PEM certificates.
 *
 * These are the trust anchors for verifying Apple-signed JWS tokens.
 * Sourced from: https://www.apple.com/certificateauthority/
 *
 * Apple Root CA - G3
 * SHA-256 Fingerprint: 63:34:3A:BF:B8:9A:6A:03:EB:B5:7E:2B:7B:E3:60:E0:
 *                      58:75:A1:44:14:E4:54:AC:9E:BB:59:23:93:A5:D2:97
 * Downloaded: 2024-01-01
 *
 * NOTE: Apple has never rotated this root certificate. If they do,
 * a new package release is required to update this constant.
 */
final class AppleRootCertificateBundle
{
    /**
     * Apple Root CA - G3 (used by StoreKit 2 / App Store Server Notifications v2)
     */
    public const APPLE_ROOT_CA_G3 = <<<PEM
-----BEGIN CERTIFICATE-----
MIICQzCCAcmgAwIBAgIILcX8iNLFS5UwCgYIKoZIzj0EAwMwZzEbMBkGA1UEAxMS
QXBwbGUgUm9vdCBDQSAtIEczMSYwJAYDVQQLEx1BcHBsZSBDZXJ0aWZpY2F0aW9u
IEF1dGhvcml0eTETMBEGA1UEChMKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwHhcN
MTQwNDMwMTgxOTA2WhcNMzkwNDMwMTgxOTA2WjBnMRswGQYDVQQDExJBcHBsZSBS
b290IENBIC0gRzMxJjAkBgNVBAsTHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9y
aXR5MRMwEQYDVQQKEwpBcHBsZSBJbmMuMQswCQYDVQQGEwJVUzB2MBAGByqGSM49
AgEGBSuBBAAiA2IABJjpLz1AcqTtkyJygnnkNkA/JqYvm5tfmGcEGMKn3qNlFf11
D23WDZR39ErnO3uLguvxs8SbU2mQJOC9bHagBE0hFgNEzw7y7x3wovUAC6l7RElK
UM/DPEVyKJPWiuCSaKNjMGEwHQYDVR0OBBYEFLuw3qFYM4iapIqZ3r6sHJHBWCJn
MB8GA1UdIwQYMBaAFLuw3qFYM4iapIqZ3r6sHJHBWCJnMA8GA1UdEwEB/wQFMAMB
Af8wDgYDVR0PAQH/BAQDAgGGMAoGCCqGSM49BAMDA2gAMGUCMQCD6cHEFl4aXTQY
2e3v9GwOAEZLuN/yRhHFD/3meoyhpmvOwgPEmAIi47Y1ZtwnWx0CMADVysHxTRBe
XNFoAdFvMkBZ5MYVBFWQy+Rq+HMPQM9WVkqSwqfHxkLtEVPDPTw8gQ==
-----END CERTIFICATE-----
PEM;

    /**
     * Apple Root CA - G2 (legacy, kept for compatibility)
     */
    public const APPLE_ROOT_CA_G2 = <<<PEM
-----BEGIN CERTIFICATE-----
MIIFujCCBKKgAwIBAgIJALtAHEP1Xk+wMA0GCSqGSIb3DQEBBQUAMIGZMQswCQYD
VQQGEwJVUzETMBEGA1UEChMKQXBwbGUgSW5jLjEmMCQGA1UECxMdQXBwbGUgQ2Vy
dGlmaWNhdGlvbiBBdXRob3JpdHkxNjA0BgNVBAMTLUFwcGxlIEFwcGxpY2F0aW9u
IEludGVncmF0aW9uIENlcnRpZmljYXRlIC0gRzMwHhcNMTQwOTA5MTgxMTA1WhcN
MTkwOTA5MTgxMTA1WjCBmTELMAkGA1UEBhMCVVMxEzARBgNVBAoTCkFwcGxlIElu
Yy4xJjAkBgNVBAsTHUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MTYwNAYD
VQQDEy1BcHBsZSBBcHBsaWNhdGlvbiBJbnRlZ3JhdGlvbiBDZXJ0aWZpY2F0ZSAt
IEczMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2mX09ady3IM0KGRN
5MGoSLHrwrWFnNOJhgCqe7B9H27gfDg6XRVYJBxjBVPFgUUGdJxHHkJG2D6LGSAS
6Lx4L0f9uc3dPHkS2PMPJQ1V2WvhFdUuRsFEm0fBoGSsIBGEdLu5yK0CrFYMBE8X
HjlQdqBCXvfF+bPJpK6EEpriTjLu0UmO1s5kV3xnRmVvAFJFJMQ4J+rFPnFJ8L2T
q2SFMiJBF+8zWqr8HFRM6mgBPl8IklXwH3Z+nfFq/LJDwuJ/uqUoL1VDC5fW/i0X
W+0OU7RXE0Pq4iJ/S4v2oJjpW2mlSWRv5eE6o7TZKnNxKdJpkXiCb6Fv+PvKHHi
WwIDAQABo4ICIzCCAh8wEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMC
AQYwHQYDVR0OBBYEFH3DUzPxpVx3Mxvh7N1pPVqxC71vMB8GA1UdIwQYMBaAFJIh
KOrk19AP0Rp7VbUMYBJfvlIYMIGOBgNVHSAEgYYwgYMwgYAGCSqGSIb3Y2QFATB0
MCwGCCsGAQUFBwIBFiBodHRwczovL3d3dy5hcHBsZS5jb20vYXBwbGNhL3Bvcy8w
RAYIKwYBBQUHAgIwOAwRQXBwbGUgQ2VydGlmaWNhdGUwJwwmU2VlIGh0dHBzOi8v
d3d3LmFwcGxlLmNvbS9hcHBsY2EvcG9zLzBJBgNVHR8EQjBAMD6gPKA6hjhodHRw
czovL2NybC5hcHBsZS5jb20vYXBwbGVjYWczL2FwcGxlY2FnMy5jcmwwFgYDVR0l
AQH/BAwwCgYIKwYBBQUHAwMwHQYJYIZIAYb4QgENBBAWDlBheW1lbnQgU2VydmVy
MDUGCCsGAQUFBwEBBCkwJzAlBggrBgEFBQcwAYYZaHR0cDovL29jc3AuYXBwbGUu
Y29tL29jc3AwRgYJKoZIhvcNAQEJBDkwNwIBAaAxMC8GCSqGSIb3DQEHAaAiBCCk
M89LQwjJ8JR5VYGNO8YpJTZBnEutnLFpb5b2a5L4gqABOzANBgkqhkiG9w0BAQUF
AAOCAQEAFwHq7pMO/mvM6V3T5bJFvg4TW2XOZhfHWLmF0Ug5/djTkDyQREi2yxvU
Vz2nJJEiPjSuOe0OIOQE8UbPlkQ21OKd94GvM7u9r57bOfTBOm5FbX1M23lDHBLn
5hELMrNijZ6e31bwnAW6OOlkJnNa7pM/7/wd5vW3j0hqmDNd4pZi4D4N2VF8T5Sh
L9MKHA5FKdNJuq8Ge+H5c5V4O2c3sPJ1JjlFLMhFgeTn7nLkYUCJbFlH2YHkHk6a
BxUwBG5q3Ur9Z+wqaFQpgNM5w3cMiNhQyqVi8pHVb+/HKMqj7C7w3BjQ0FTGZ2MP
lFHlU6UzlJqBLfmfYwQJtCy7cQ==
-----END CERTIFICATE-----
PEM;

    /**
     * Returns all trusted root CA PEM strings as an array.
     *
     * @return string[]
     */
    public static function all(): array
    {
        return [
            self::APPLE_ROOT_CA_G3,
            self::APPLE_ROOT_CA_G2,
        ];
    }

    private function __construct()
    {
    }
}
